management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 12345

#自定义路由
zuul:
  routes:
    configserver:
      path: /myConfig/**
      serviceId: config
    user:
      path: /myUser/**
      serviceId: provider
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
#  ignore-local-service: true  忽略自定的路由
  ignored-patterns:
      - /config/**
      - /provider/**
  sensitive-headers: #允许所有敏感信息头
