spring:
  cloud:
    zookeeper:
      connect-string: 47.107.133.173:2181
      discovery:
        register: false
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true